// <auto-generated />
namespace ShoolsLMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class InitialData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialData));
        
        string IMigrationMetadata.Id
        {
            get { return "202102121731551_InitialData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
